index:
   path: /
   controller: App\Controller\WelcomeController::index

currencies_index:
   path: /currencies
   controller: App\Controller\CurrencyController::index

currencies_show:
   path: /currencies/{id}
   controller: App\Controller\CurrencyController::show
   requirements:
        id: '\d+'