index:
   path: /
   controller: App\Controller\WelcomeController::index

currencies_index:
   path: /currencies
   controller: App\Controller\CurrencyController::index

currencies_show:
   path: /currencies/{id}
   controller: App\Controller\CurrencyController::show
   requirements:
        id: '\d+'

change_index:
   path: /change
   controller: App\Controller\ChangeController::index

order_store:
   path: /order
   controller: App\Controller\OrderController::store
   methods: POST
