index:
   path: /
   controller: App\Controller\WelcomeController::index

currencies_index:
   path: /currencies
   controller: App\Controller\CurrencyController::index

currencies_show:
   path: /currencies/{id}
   requirements:
        page: '\d+'