parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Service/*'
    
    app.service.cbrf_currency_loader:
        class: App\Service\CBRFRatesLoader